spring:
  application:
        name: server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/messenger_pg_db
    password: password
    username: postgres